INSERT INTO TB_CATEGORY (NAME, created_at) VALUES ('BOOKS', NOW());
INSERT INTO TB_CATEGORY (NAME, created_at) VALUES ('ELECTRONICS', NOW());
INSERT INTO TB_CATEGORY (NAME, created_at) VALUES ('COMPUTERS', NOW());